


#spring.data.mongodb.uri = mongodb+srv://prashantkum7676_db_user:YpoNTgXHy22NtUPV@cluster0.he4vd3t.mongodb.net/?appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://prashantkum7676_db_user:YpoNTgXHy22NtUPV@cluster0.he4vd3t.mongodb.net/journal?appName=Cluster0

spring.data.mongodb.database=journal
spring.data.mongodb.auto-index-creation=true
